# Generated by Django 4.2.1 on 2023-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partygroup',
            name='current_time',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=100),
        ),
    ]
