# Generated by Django 4.2.1 on 2023-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyapp', '0002_alter_partygroup_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='partygroup',
            name='new_member',
            field=models.BooleanField(default=False),
        ),
    ]
